services:
  backend:
    image: backend:v1
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - app-net
    environment:
      MCP_RAG_URL: http://mcp-rag:8001/mcp
      MCP_WEB_URL: http://mcp-web:8002/mcp
      MCP_MEMORY_URL: http://mcp-memory:8003/mcp
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  
  mcp-rag:
    image: mcp-rag:v1
    build:
      context: .
      dockerfile: Dockerfile.rag
    ports:
      - "8001:8001"
    networks:
      - app-net
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  mcp-web:
    image: mcp-web:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8002:8002"
    networks:
      - app-net
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  mcp-memory:
    image: mcp-memory:v1
    build:
      context: .
      dockerfile: Dockerfile.memory
    ports:
      - "8003:8003"
    networks:
      - app-net
    develop:
      watch:
        - action: sync
          path: .
          target: /app

networks:
  app-net:
    driver: bridge